//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCEntities1 : DbContext
    {
        public NCEntities1()
            : base("name=NCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Fichos> Tbl_Fichos { get; set; }
        public virtual DbSet<Tbl_Grados> Tbl_Grados { get; set; }
        public virtual DbSet<Tbl_Grados_Fichos> Tbl_Grados_Fichos { get; set; }
        public virtual DbSet<Tbl_Modulos> Tbl_Modulos { get; set; }
        public virtual DbSet<Tbl_Operaciones> Tbl_Operaciones { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_Roles_Operaciones> Tbl_Roles_Operaciones { get; set; }
        public virtual DbSet<Tbl_Usuarios> Tbl_Usuarios { get; set; }
    }
}
