//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Fichos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Fichos()
        {
            this.Tbl_Grados_Fichos = new HashSet<Tbl_Grados_Fichos>();
        }
    
        public int IdFicho { get; set; }

        [Required(ErrorMessage = "¡Este campo es requerido si desea reservar el cupo!")]
        [DataType(DataType.Date)]
        public System.DateTime FechaFicho { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Grados_Fichos> Tbl_Grados_Fichos { get; set; }
        public virtual Tbl_Usuarios Tbl_Usuarios { get; set; }
    }
}
