//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Roles_Operaciones
    {
        public int IdRolOperacion { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdOperacion { get; set; }
    
        public virtual Tbl_Operaciones Tbl_Operaciones { get; set; }
        public virtual Tbl_Roles Tbl_Roles { get; set; }
    }
}
