//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Grados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Grados()
        {
            this.Tbl_Grados_Fichos = new HashSet<Tbl_Grados_Fichos>();
        }
    
        public int IdGrado { get; set; }
        public string NombreGrado { get; set; }
        public string JornadaGrado { get; set; }
        public string DisponibilidadCupoGrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Grados_Fichos> Tbl_Grados_Fichos { get; set; }
    }
}
