//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Operaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Operaciones()
        {
            this.Tbl_Roles_Operaciones = new HashSet<Tbl_Roles_Operaciones>();
        }
    
        public int IdOperacion { get; set; }
        public string NombreOperacion { get; set; }
        public Nullable<int> IdModulo { get; set; }
    
        public virtual Tbl_Modulos Tbl_Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Roles_Operaciones> Tbl_Roles_Operaciones { get; set; }
    }
}
