//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Grados_Fichos
    {
        public int IdGRadosFichos { get; set; }
        public Nullable<int> IdFicho { get; set; }
        public Nullable<int> IdGrado { get; set; }
    
        public virtual Tbl_Fichos Tbl_Fichos { get; set; }
        public virtual Tbl_Grados Tbl_Grados { get; set; }
    }
}
